#This section is all about numpy 
##numpy is used for scientific computations.
Provides support for arrays and matrices 
conain mathematical functions to operate on these data structures

In [1]:
import numpy as np

In [2]:
#creating an array using numpy
arr1=np.array([1,2,3,4,5])# this is one dim array 
print(arr1)

[1 2 3 4 5]


In [ ]:
arr1.shape #means 5 elements in array

(5,)

In [25]:
#creating 2 dim array 
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1)
arr1.ndim

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2

In [15]:
arr1.shape #means 2 rows of 5 elements

(2, 5)

In [26]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1.reshape(1,5))
arr1.ndim

[1 2 3 4 5]
[[1 2 3 4 5]]


1

In [29]:

import numpy.char as char

In [34]:

arr2=np.arange(0,10,2)#creates an array starting from 0 to 10 2 is stepsize

arr2

array([0, 2, 4, 6, 8])

In [39]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
#attritubutes in numpy
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)
print(arr1.itemsize)
print(arr1.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
10
2
8
int64


In [42]:
#universal operations in numpy
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print("addition =", arr1+arr2)
print("subtraction=", arr1-arr2)
print("multiplication =", arr1*arr2)
print("division =", arr1/arr2)

addition = [ 7  9 11 13 15]
subtraction= [-5 -5 -5 -5 -5]
multiplication = [ 6 14 24 36 50]
division = [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [49]:
# universal functions 
arr2=np.array([6,7,8,9,10])
a=np.sqrt([arr2])
print('squre root=',a)
b=np.exp([arr2])
print('exponent=',b)
c=np.sin([arr2])
print('sin=',c)
d=np.log([arr2])
print('natural log=',d)

squre root= [[2.44948974 2.64575131 2.82842712 3.         3.16227766]]
exponent= [[  403.42879349  1096.63315843  2980.95798704  8103.08392758
  22026.46579481]]
sin= [[-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]]
natural log= [[1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]]


In [51]:
# array slicing and indexing 
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
arr1


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [52]:
arr1[0]

array([1, 2, 3, 4, 5])

In [53]:
arr1[0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [55]:
print(arr1[0][2])

3


In [57]:
print(arr1[1:,3:])

[[ 9 10]
 [14 15]]


In [64]:
print(arr1)
print(arr1[2:3,3])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[14]


In [68]:
#modigying array elements
arr1[0][0]=100
print(arr1)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [69]:
arr1[1:2,3]=100
print(arr1)

[[100   2   3   4   5]
 [  6   7   8 100  10]
 [ 11  12  13  14  15]]


In [73]:
#normalization using numpy
arr1=np.array([1,2,3,4,5])
mean=np.mean(arr1)
std=np.std(arr1)
normalization=arr1 - mean / std
print(normalization)

[-1.12132034 -0.12132034  0.87867966  1.87867966  2.87867966]


In [74]:
#stats opearation 
arr1=np.array([1,2,3,4,5])
print(np.mean(arr1))
print(np.std(arr1))
print(np.var(arr1))
print(np.median(arr1))

3.0
1.4142135623730951
2.0
3.0


In [77]:
#logical operations 
data=np.array([1,2,3,4,5,6,7,8,9,10])
print(data>5)
a=data[(data>5) & (data<=8)]
print(a)

[False False False False False  True  True  True  True  True]
[6 7 8]
